spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms_order?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9193
