version: "3"
services:
  token-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=cms_authDB

  token-jdbc:
    image: token-jdbc
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://token-db:3306/cms_authDB
    depends_on:
      - token-db
